#!/bin/sh

SERVERMAC="EC:1A:59:EC:1C:A9"
SERVERPORT="49153"
SERVERIP=`arp -a | grep $SERVERMAC | cut -d "(" -f2 | cut -d ")" -f1`
BINPATH="bin"
SERVERIP=192.168.1.115

setState () {
SEND="<?xml version=\"1.0\" encoding=\"utf-8\"?>
<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
   <s:Body>
      <u:SetBinaryState xmlns:u=\"urn:Belkin:service:basicevent:1\">
         <BinaryState>$1</BinaryState>
      </u:SetBinaryState>
   </s:Body>
</s:Envelope>"

$BINPATH/curl \
-H "SOAPAction: \"urn:Belkin:service:basicevent:1#SetBinaryState\"" \
-H "Content-Type: text/xml" \
-H "Accept:" \
-A "" \
-d "$SEND" \
-X POST http://$SERVERIP:$SERVERPORT/upnp/control/basicevent1
}

getState () {
$BINPATH/curl \
-H "Content-Type: text/xml" \
-H "Accept:" \
-A "" \
-X GET http://$SERVERIP:$SERVERPORT/
}

case $1 in
	on)
		setState 1
		;;
	off)
		setState 0
		;;
	status)
		echo "Function not completed yet"
		;;
	*)
		echo "usage: lightSet (on|off|status)"
		;;
esac
