#!/bin/sh

CLIENTMAC=""
BINPATH=""

STATE=`wl assoclist | grep $CLIENTMAC | wc -l`
PREVSTATE=`cat phoneState`
echo $STATE > phoneState
DIFF=`expr $PREVSTATE - $STATE`
echo $DIFF
case $DIFF in
	0)
		#No change
		;;
	-1)
		#Turn on
		$BINPATH/setWemo on
		;;
	1)
		#Turn off
		$BINPATH/setWemo off
		;;
esac
