#!/bin/sh

SERVERMAC=""
SERVERPORT="49153"
SERVERIP=`arp -a | grep $SERVERMAC | cut -d "(" -f2 | cut -d ")" -f1`

setState () {
SEND="<?xml version=\"1.0\" encoding=\"utf-8\"?>
<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
   <s:Body>
      <u:SetBinaryState xmlns:u=\"urn:Belkin:service:basicevent:1\">
         <BinaryState>$1</BinaryState>
      </u:SetBinaryState>
   </s:Body>
</s:Envelope>"

OUT=`wget -qO- \
--header="SOAPAction: \"urn:Belkin:service:basicevent:1#SetBinaryState\"" \
--header="Content-Type: text/xml" \
--header="Accept:" \
-U="" \
--post-data="$SEND" \
http://$SERVERIP:$SERVERPORT/upnp/control/basicevent1 | less`

getState
}

getState () {

SEND="<?xml version=\"1.0\" encoding=\"utf-8\"?>
<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
   <s:Body>
      <u:GetBinaryState xmlns:u=\"urn:Belkin:service:basicevent:1\"></u:GetBinaryState>
   </s:Body>
</s:Envelope>"

OUT=`wget -qO- \
--header="SOAPAction: \"urn:Belkin:service:basicevent:1#GetBinaryState\"" \
--header="Content-Type: text/xml" \
--header="Accept:" \
-U="" \
--post-data="$SEND" \
http://$SERVERIP:$SERVERPORT/upnp/control/basicevent1 | less \
| grep "</BinaryState>" | sed 's/<[^>]\+>//g'`

echo $OUT
}

case $1 in
	on)
		setState 1
		;;
	off)
		setState 0
		;;
	status)
		getState
		;;
	*)
		echo "usage: lightSet (on|off|status)"
		;;
esac
